// build.mjs — renders every SVG in /cosmos from stats.json + signals.json. Zero dependencies.
import { readFileSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { prepFonts } from './kit.mjs';
import { hero } from './art-hero.mjs';
import { galaxy } from './art-galaxy.mjs';
import { derive } from './derive.mjs';
import { terminal } from './art-terminal.mjs';
import { system } from './art-system.mjs';
import { missionPatch, sceneF1, scenePulse, sceneNight, sceneControl } from './art-missions.mjs';
import { fmtInt } from './kit.mjs';
import { signals, signalButton } from './art-signals.mjs';
import { header, combo, footer } from './art-misc.mjs';
import { galaxySTL } from './stl.mjs';

const DIR = dirname(fileURLToPath(import.meta.url));
const read = (f) => readFileSync(join(DIR, f));
const fonts = prepFonts(JSON.parse(read('glyphs.json')));
const stats = JSON.parse(read('stats.json'));
const only = process.argv[2];
// SIGNALS_FILE / AVATARS_FILE let local tests render fixtures without touching the real data
const sigList = JSON.parse(process.env.SIGNALS_FILE ? readFileSync(process.env.SIGNALS_FILE) : read('signals.json'));
const avatars = JSON.parse(process.env.AVATARS_FILE ? readFileSync(process.env.AVATARS_FILE) : read('avatars.json'));
const d = derive(stats);

const roles = [
  'game dev — co-op horror FPS in three.js',
  'procedural filmmaker — 4K F1 film, 100% code',
  'rust hacker — terminals that survive reboots',
  'AI agent wrangler — mission control for agents',
  '3D graphics nerd — Blender bpy + three.js',
  'full-stack TypeScript dev',
  'all of the above.',
];

const planets = [
  { name: 'RUST', sub: 'pulse · terminals that never die', orbit: 165, size: 10, period: 17, phase: 0.15, color: '#ff7a45', light: '#ffb38a', dark: '#6b1d0a', moon: 6 },
  { name: 'PYTHON + BLENDER', sub: 'bpy · cycles · procedural film', orbit: 255, size: 15, period: 25, phase: 0.62, color: '#4f7dff', light: '#ffd36e', dark: '#13205c', ring: true },
  { name: 'GAME DEV', sub: 'three.js · node · uWebSockets', orbit: 345, size: 13, period: 34, phase: 0.36, color: '#22d39a', light: '#8affd2', dark: '#06402d', bands: true, moon: 9 },
  { name: 'TYPESCRIPT', sub: 'electron · tanstack · sqlite', orbit: 435, size: 16, period: 45, phase: 0.83, color: '#3b82f6', light: '#9cc3ff', dark: '#0b2a63', ring: true },
  { name: 'AI AGENTS', sub: 'claude code · codex · cursor', orbit: 520, size: 12, period: 58, phase: 0.05, color: '#ff3dbb', light: '#ff9be0', dark: '#5c0b43', moon: 5 },
];

const ms = d.missions;
const mc = (k) => ms[k] || {};
const missions = [
  { key: 'f1', repo: 'aipulsedaily/f1-round2', file: 'mission-f1', accent: '#ff4d5e', accent2: '#ffb84d', glow: '#5a1430', ringTop: 'F1 • ROUND 2', ringBottom: '4K • ONE TAKE • 100% CODE', scene: sceneF1,
    desc: 'A 124-second 4K film of an F1 car in one unbroken take. Every model, material and sound is generated by code.',
    chips: () => [[`${fmtInt(mc('aipulsedaily/f1-round2').commits)} COMMITS`, '#ffb84d'], [`★ ${mc('aipulsedaily/f1-round2').stars}`, '#ffd36e'], ['PYTHON · BLENDER', '#ff7a8a']], badge: () => mc('aipulsedaily/f1-round2').rank === 1 ? 'TOP CONTRIBUTOR' : null },
  { key: 'pulse', repo: 'aipulsedaily/pulse', file: 'mission-pulse', accent: '#2df5c7', accent2: '#7dffe0', glow: '#0c3b3a', ringTop: 'PULSE', ringBottom: 'TERMINALS THAT SURVIVE REBOOTS', scene: scenePulse,
    desc: 'A persistent terminal manager for Windows. Your sessions survive reboots.',
    chips: () => [[`${fmtInt(mc('aipulsedaily/pulse').commits)} COMMITS`, '#7dffe0'], [`★ ${mc('aipulsedaily/pulse').stars}`, '#ffd36e'], ['RUST', '#ff9a6b']], badge: () => mc('aipulsedaily/pulse').rank === 1 ? 'TOP CONTRIBUTOR' : null },
  { key: 'night', repo: 'webdevcody/survive-the-night-fps', file: 'mission-night', accent: '#ff3b3b', accent2: '#ffcc66', glow: '#3a0b14', ringTop: 'SURVIVE THE NIGHT', ringBottom: 'CO-OP HORROR FPS • THREE.JS', scene: sceneNight,
    desc: 'Co-op horror survival FPS. Scavenge by day, board up by night, fix the car and escape.',
    chips: () => [[`${fmtInt(mc('webdevcody/survive-the-night-fps').commits)} COMMITS`, '#ffcc66'], [`★ ${mc('webdevcody/survive-the-night-fps').stars}`, '#ffd36e'], ['THREE.JS · NODE', '#ff7a7a']], badge: () => mc('webdevcody/survive-the-night-fps').rank === 1 ? 'TOP CONTRIBUTOR' : null },
  { key: 'control', repo: 'AgentSystemLabs/mission-control', file: 'mission-control', accent: '#b18cff', accent2: '#ff9be0', glow: '#25104d', ringTop: 'MISSION CONTROL', ringBottom: 'COMMAND CENTER FOR AI AGENTS', scene: sceneControl,
    desc: 'A desktop command center for agentic coding. Every project, every agent, one view.',
    chips: () => [[`${fmtInt(mc('AgentSystemLabs/mission-control').commits)} COMMITS`, '#d7c2ff'], [`★ ${mc('AgentSystemLabs/mission-control').stars}`, '#ffd36e'], ['TYPESCRIPT · ELECTRON', '#9cc3ff']], badge: () => mc('AgentSystemLabs/mission-control').rank === 1 ? 'TOP CONTRIBUTOR' : null },
];

export const SECTIONS = [
  ['01', 'TRANSMISSION', '// who is SCG'],
  ['02', 'COMMIT GALAXY', '// my last 365 days, one star per day'],
  ['03', 'THE SCG SYSTEM', '// everything I build with'],
  ['04', 'MISSIONS', "// things I've launched"],
  ['05', 'SEND A SIGNAL', '// become a star in this sky'],
  ['06', '? ? ?', '// only the worthy know the combo'],
];

const jobs = {
  hero: () => hero({ fonts, nebula: read('nebula-hero.jpg'), data: { roles, lifetime: d.lifetime, since: d.since } }),
  transmission: () => terminal({ fonts, d, missions: d.missions }),
  system: () => system({ fonts, planets }),
  ...Object.fromEntries(missions.map((m, i) => [m.file, () => missionPatch({ fonts, index: i + 1, m: { ...m, chips: m.chips(), badge: m.badge() } })])),
  signals: () => signals({ fonts, bg: read('nebula-signals.jpg'), list: sigList, avatars, owner: { avatar: avatars.owner } }),
  'btn-signal': () => signalButton({ fonts, variant: 'signal' }),
  'btn-combo': () => signalButton({ fonts, variant: 'combo' }),
  ...Object.fromEntries(SECTIONS.flatMap(([num, title, sub]) => ['dark', 'light'].map((theme) => [`h-${num}-${theme}`, () => header({ fonts, num, title, sub, theme, total: SECTIONS.length })]))),
  combo: () => combo({ fonts }),
  'footer-dark': () => footer({ fonts, bg: read('nebula-footer.jpg'), theme: 'dark', d }),
  'footer-light': () => footer({ fonts, bg: null, theme: 'light', d }),
  galaxy: () => galaxy({ fonts, bg: read('nebula-galaxy.jpg'), spiral: read('spiral.jpg'), d }),
};

for (const [name, fn] of Object.entries(jobs)) {
  if (only && only !== name) continue;
  const svg = fn();
  writeFileSync(join(DIR, `${name}.svg`), svg);
  console.log(`${name}.svg`, (Buffer.byteLength(svg) / 1024).toFixed(1) + ' KB');
}

// legacy outputs from earlier versions of the engine
for (const old of ['skyline.stl']) if (existsSync(join(DIR, old))) rmSync(join(DIR, old));

// ---- README live sections ----
if (!only || only === 'readme') {
  const stl = galaxySTL(d.cal);
  writeFileSync(join(DIR, 'galaxy.stl'), stl + '\n');
  const readmePath = join(DIR, '..', 'README.md');
  let md = readFileSync(readmePath, 'utf8');
  const put = (key, content) => {
    const re = new RegExp(`(<!-- ${key}:START -->)[\\s\\S]*?(<!-- ${key}:END -->)`);
    md = md.replace(re, (_, a, b) => `${a}\n${content}\n${b}`);
  };
  put('HOLOGRAM', [
    '<details>',
    `<summary><b>🛰️ HOLOGRAM</b> — grab it, spin it: the commit galaxy in 3D (${fmtInt(d.rolling)} contributions)</summary>`,
    '',
    '```stl',
    stl,
    '```',
    '',
    '<sub>one tower per active day, on the same spiral arms as the galaxy above · height = contributions · drag to orbit · <a href="cosmos/galaxy.stl">open full screen</a></sub>',
    '</details>',
  ].join('\n'));
  const latest = sigList.slice(-12).reverse();
  put('SIGNALS', latest.length
    ? `<sub>📡 latest signals: ${latest.map((x) => `<a href="https://github.com/${x.login}">@${x.login}</a>${x.combo ? ' ✨' : ''}`).join(' · ')}</sub>`
    : '<sub>📡 no signals yet. the first star in this sky could be yours.</sub>');
  put('SYNC', `<sub>🛰️ telemetry synced <b>${d.today}</b> · this profile rebuilds itself every day from <a href="cosmos">/cosmos</a> · zero dependencies · <a href="#top">back to launch ↑</a></sub>`);
  writeFileSync(readmePath, md);
  console.log('README.md', (Buffer.byteLength(md) / 1024).toFixed(1) + ' KB', '· galaxy.stl', (stl.length / 1024).toFixed(1) + ' KB');
}
